#ifndef MACRODEFS_HPP
#define MACRODEFS_HPP

#define LANE_SIZE 5
#define ITERATION_DISTANCE_X windowSize.x/7
#define ITERATION_DISTANCE_Y windowSize.y/10
#define TURN_PHASE_LENGTH  3000
#define BATTLE_PHASE_DELAY TURN_PHASE_LENGTH/6
#endif