make:
	g++ game.cpp exeptions.cpp objectStorage.cpp operators.cpp character.cpp titlecard.cpp background.cpp button.cpp renderer.cpp card.cpp main.cpp -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -o main.exe

run:
	make
	./main.exe

clean:
	rm main.exe